
var Module = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,k,ba=new Promise((a,b)=>{aa=a;k=b}),ca="object"==typeof window,da="undefined"!=typeof WorkerGlobalScope,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;const q=[],ea=[];g.print=a=>q.push(a);g.printErr=a=>ea.push(a);var fa=Object.assign({},g),ha="./this.program",u=(a,b)=>{throw b;},v="",ia,w;
if(m){var fs=require("fs"),ja=require("path");v=__dirname+"/";w=a=>{a=x(a)?new URL(a):ja.normalize(a);return fs.readFileSync(a)};ia=a=>{a=x(a)?new URL(a):ja.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!g.thisProgram&&1<process.argv.length&&(ha=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);u=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||da)da?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),
_scriptName&&(v=_scriptName),v=v.startsWith("blob:")?"":v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1),da&&(w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>x(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?
b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ka=g.print||console.log.bind(console),y=g.printErr||console.error.bind(console);Object.assign(g,fa);fa=null;g.thisProgram&&(ha=g.thisProgram);var oa=g.wasmBinary,pa,qa=!1,ra,z,A,sa,B,C;
function ta(){var a=pa.buffer;g.HEAP8=z=new Int8Array(a);g.HEAP16=sa=new Int16Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAP32=B=new Int32Array(a);g.HEAPU32=C=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var ua=[],va=[],wa=[];function xa(){var a=g.preRun.shift();ua.unshift(a)}var D=0,ya=null,E=null;
function za(a){g.onAbort?.(a);a="Aborted("+a+")";y(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");k(a);throw a;}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),x=a=>a.startsWith("file://"),Ba;function Ca(a){if(a==Ba&&oa)return new Uint8Array(oa);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}function Da(a){return oa?Promise.resolve().then(()=>Ca(a)):ia(a).then(b=>new Uint8Array(b),()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{y(`failed to asynchronously prepare wasm: ${d}`);za(d)})}function Fa(a,b){var c=Ba;return oa||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||x(c)||m||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){y(`wasm streaming compile failed: ${e}`);y("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}var F,Ga;
class Ha{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ia=a=>{for(;0<a.length;)a.shift()(g)},Ja=g.noExitRuntime||!0;class Ka{constructor(a){this.aa=a-24}}
var La=0,Oa=0,H=()=>{var a=B[+G>>2];G+=4;return a},Pa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},J=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Pa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=
b.substr(0,b.length-1);return a+b},Ra=a=>{if("/"===a)return"/";a=J(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Sa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(m)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}za("initRandomDevice")},Ta=a=>(Ta=Sa())(a),Ua=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=
d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Pa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Va="undefined"!=typeof TextDecoder?new TextDecoder:void 0,K=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Va)return Va.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|
f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Wa=[],Xa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},L=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);
h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},Ya=[];function Za(a,b){Ya[a]={input:[],output:[],V:b};$a(a,ab)}
var ab={open(a){var b=Ya[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close(a){a.tty.V.fsync(a.tty)},fsync(a){a.tty.V.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.V.ma)throw new N(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.V.ma(a.tty)}catch(n){throw new N(29);}if(void 0===h&&0===e)throw new N(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.V.ga)throw new N(60);try{for(var e=0;e<d;e++)a.tty.V.ga(a.tty,b[c+e])}catch(f){throw new N(29);
}d&&(a.node.timestamp=Date.now());return e}},bb={ma(){a:{if(!Wa.length){var a=null;if(m){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Xa(a)+1);a=L(a,b,0,b.length);b.length=a;Wa=b}a=Wa.shift()}return a},ga(a,b){null===b||10===b?
(ka(K(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ka(K(a.output)),a.output=[])},wa(){return{Fa:25856,Ha:5,Ea:191,Ga:35387,Da:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},xa(){return 0},ya(){return[24,80]}},cb={ga(a,b){null===b||10===b?(y(K(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(y(K(a.output)),a.output=[])}};
function db(a,b){var c=a.O?a.O.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.O,a.O=new Uint8Array(b),0<a.R&&a.O.set(c.subarray(0,a.R),0))}
var O={S:null,U(){return O.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.S||(O.S={dir:{node:{W:O.N.W,T:O.N.T,lookup:O.N.lookup,Z:O.N.Z,rename:O.N.rename,unlink:O.N.unlink,rmdir:O.N.rmdir,readdir:O.N.readdir,symlink:O.N.symlink},stream:{Y:O.P.Y}},file:{node:{W:O.N.W,T:O.N.T},stream:{Y:O.P.Y,read:O.P.read,write:O.P.write,ia:O.P.ia,oa:O.P.oa,qa:O.P.qa}},link:{node:{W:O.N.W,T:O.N.T,readlink:O.N.readlink},stream:{}},ja:{node:{W:O.N.W,T:O.N.T},
stream:eb}});c=fb(a,b,c,d);16384===(c.mode&61440)?(c.N=O.S.dir.node,c.P=O.S.dir.stream,c.O={}):32768===(c.mode&61440)?(c.N=O.S.file.node,c.P=O.S.file.stream,c.R=0,c.O=null):40960===(c.mode&61440)?(c.N=O.S.link.node,c.P=O.S.link.stream):8192===(c.mode&61440)&&(c.N=O.S.ja.node,c.P=O.S.ja.stream);c.timestamp=Date.now();a&&(a.O[b]=c,a.timestamp=c.timestamp);return c},Ja(a){return a.O?a.O.subarray?a.O.subarray(0,a.R):new Uint8Array(a.O):new Uint8Array(0)},N:{W(a){var b={};b.dev=8192===(a.mode&61440)?a.id:
1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.R:40960===(a.mode&61440)?a.link.length:0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ta=4096;b.blocks=Math.ceil(b.size/b.ta);return b},T(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.R!=b))if(0==b)a.O=null,a.R=0;else{var c=a.O;a.O=new Uint8Array(b);c&&a.O.set(c.subarray(0,
Math.min(b,a.R)));a.R=b}},lookup(){throw gb[44];},Z(a,b,c,d){return O.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=hb(b,c)}catch(f){}if(d)for(var e in d.O)throw new N(55);}delete a.parent.O[a.name];a.parent.timestamp=Date.now();a.name=c;b.O[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.O[b];a.timestamp=Date.now()},rmdir(a,b){var c=hb(a,b),d;for(d in c.O)throw new N(55);delete a.O[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.O))b.push(c);
return b},symlink(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},P:{read(a,b,c,d,e){var f=a.node.O;if(e>=a.node.R)return 0;a=Math.min(a.node.R-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===z.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.O||a.O.subarray)){if(f)return a.O=b.subarray(c,c+d),a.R=d;if(0===a.R&&0===
e)return a.O=b.slice(c,c+d),a.R=d;if(e+d<=a.R)return a.O.set(b.subarray(c,c+d),e),d}db(a,e+d);if(a.O.subarray&&b.subarray)a.O.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.O[e+f]=b[c+f];a.R=Math.max(a.R,e+d);return d},Y(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.R);if(0>b)throw new N(28);return b},ia(a,b,c){db(a.node,b+c);a.node.R=Math.max(a.node.R,b+c)},oa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.O;if(e&2||!a||a.buffer!==z.buffer){d=!0;za();
e=void 0;if(!e)throw new N(48);if(a){if(0<c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{aa:e,Ca:d}},qa(a,b,c,d){O.P.write(a,b,0,d,c,!1);return 0}}},ib=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},jb=null,kb={},P=[],lb=1,Q=null,mb=!1,nb=!0,N=class{name="ErrnoError";constructor(a){this.X=a}},gb={},ob={},pb=class{da={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.da.flags}set flags(a){this.da.flags=
a}get position(){return this.da.position}set position(a){this.da.position=a}},qb=class{N={};P={};ba=365;ea=146;$=null;constructor(a,b,c,d){a||=this;this.parent=a;this.U=a.U;this.id=lb++;this.name=b;this.mode=c;this.rdev=d}get read(){return(this.mode&this.ba)===this.ba}set read(a){a?this.mode|=this.ba:this.mode&=~this.ba}get write(){return(this.mode&this.ea)===this.ea}set write(a){a?this.mode|=this.ea:this.mode&=~this.ea}};
function R(a,b={}){a=Ua(a);if(!a)return{path:"",node:null};b=Object.assign({la:!0,ha:0},b);if(8<b.ha)throw new N(32);a=a.split("/").filter(h=>!!h);for(var c=jb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=hb(c,a[e]);d=J(d+"/"+a[e]);c.$&&(!f||f&&b.la)&&(c=c.$.root);if(!f||b.ka)for(f=0;40960===(c.mode&61440);)if(c=rb(d),d=Ua(Qa(d),c),c=R(d,{ha:b.ha+1}).node,40<f++)throw new N(32);}return{path:d,node:c}}
function sb(a){for(var b;;){if(a===a.parent)return a=a.U.pa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function hb(a,b){var c=16384===(a.mode&61440)?(c=ub(a,"x"))?c:a.N.lookup?0:2:54;if(c)throw new N(c);for(c=Q[tb(a.id,b)];c;c=c.Aa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.N.lookup(a,b)}
function fb(a,b,c,d){a=new qb(a,b,c,d);b=tb(a.parent.id,a.name);a.Aa=Q[b];return Q[b]=a}function vb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ub(a,b){if(nb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function wb(a,b){try{return hb(a,b),20}catch(c){}return ub(a,"wx")}function S(a){a=P[a];if(!a)throw new N(8);return a}
function xb(a,b=-1){a=Object.assign(new pb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!P[b])break a;throw new N(33);}a.fd=b;return P[b]=a}function yb(a,b=-1){a=xb(a,b);a.P?.Ia?.(a);return a}var eb={open(a){a.P=kb[a.node.rdev].P;a.P.open?.(a)},Y(){throw new N(70);}};function $a(a,b){kb[a]={P:b}}
function zb(a,b){var c="/"===b;if(c&&jb)throw new N(10);if(!c&&b){var d=R(b,{la:!1});b=d.path;d=d.node;if(d.$)throw new N(10);if(16384!==(d.mode&61440))throw new N(54);}b={type:a,Ka:{},pa:b,za:[]};a=a.U(b);a.U=b;b.root=a;c?jb=a:d&&(d.$=b,d.U&&d.U.za.push(b))}function Ab(a,b,c){var d=R(a,{parent:!0}).node;a=Ra(a);if(!a||"."===a||".."===a)throw new N(28);var e=wb(d,a);if(e)throw new N(e);if(!d.N.Z)throw new N(63);return d.N.Z(d,a,b,c)}function T(a){return Ab(a,16895,0)}
function Bb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Ab(a,b|8192,c)}function Cb(a,b){if(!Ua(a))throw new N(44);var c=R(b,{parent:!0}).node;if(!c)throw new N(44);b=Ra(b);var d=wb(c,b);if(d)throw new N(d);if(!c.N.symlink)throw new N(63);c.N.symlink(c,b,a)}function rb(a){a=R(a).node;if(!a)throw new N(44);if(!a.N.readlink)throw new N(28);return Ua(sb(a.parent),a.N.readlink(a))}
function U(a,b,c){if(""===a)throw new N(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=J(a);try{e=R(a,{ka:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new N(20);}else e=Ab(a,c,0),d=!0;if(!e)throw new N(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new N(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==vb(b)||b&512)?31:ub(e,vb(b)):44))throw new N(c);if(b&512&&!d){c=e;c="string"==typeof c?R(c,{ka:!0}).node:c;if(!c.N.T)throw new N(63);if(16384===(c.mode&61440))throw new N(31);if(32768!==(c.mode&61440))throw new N(28);if(d=ub(c,"w"))throw new N(d);c.N.T(c,{size:0,timestamp:Date.now()})}b&=-131713;e=xb({node:e,path:sb(e),flags:b,seekable:!0,position:0,P:e.P,Ba:[],error:!1});e.P.open&&e.P.open(e);!g.logReadFiles||b&1||a in ob||(ob[a]=
1);return e}function Db(a){if(null===a.fd)throw new N(8);a.fa&&(a.fa=null);try{a.P.close&&a.P.close(a)}catch(b){throw b;}finally{P[a.fd]=null}a.fd=null}function Eb(a,b,c){if(null===a.fd)throw new N(8);if(!a.seekable||!a.P.Y)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.P.Y(a,b,c);a.Ba=[]}
function Fb(a,b,c,d,e,f){if(0>d||0>e)throw new N(28);if(null===a.fd)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(16384===(a.node.mode&61440))throw new N(31);if(!a.P.write)throw new N(28);a.seekable&&a.flags&1024&&Eb(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new N(70);b=a.P.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function Gb(a){var b={};b.flags=b.flags||577;var c=U("m.lp",b.flags,b.mode);if("string"==typeof a){var d=new Uint8Array(Xa(a)+1);a=L(a,d,0,d.length);Fb(c,d,0,a,void 0,b.ua)}else if(ArrayBuffer.isView(a))Fb(c,a,0,a.byteLength,void 0,b.ua);else throw Error("Unsupported data type");Db(c)}
function V(a,b,c){a=J("/dev/"+a);var d=ib(!!b,!!c);V.na??(V.na=64);var e=V.na++<<8|0;$a(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,h,n,t){for(var l=0,p=0;p<t;p++){try{var r=b()}catch(I){throw new N(29);}if(void 0===r&&0===l)throw new N(6);if(null===r||void 0===r)break;l++;h[n+p]=r}l&&(f.node.timestamp=Date.now());return l},write(f,h,n,t){for(var l=0;l<t;l++)try{c(h[n+l])}catch(p){throw new N(29);}t&&(f.node.timestamp=Date.now());return l}});Bb(a,d,e)}
var W={},G=void 0,Hb=0,X={},Ib=a=>{ra=a;Ja||0<Hb||(g.onExit?.(a),qa=!0);u(a,new Ha(a))},Jb=a=>{if(!qa)try{if(a(),!(Ja||0<Hb))try{ra=a=ra,Ib(a)}catch(b){b instanceof Ha||"unwind"==b||u(1,b)}}catch(b){b instanceof Ha||"unwind"==b||u(1,b)}},Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ha||"./this.program"},b;for(b in Kb)void 0===Kb[b]?
delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Qb=(a,b,c,d)=>{var e={string:l=>{var p=0;if(null!==l&&void 0!==l&&0!==l){p=Xa(l)+1;var r=Nb(p);L(l,A,r,p);p=r}return p},array:l=>{var p=Nb(l.length);z.set(l,p);return p}};a=g["_"+a];var f=[],h=0;if(d)for(var n=0;n<d.length;n++){var t=e[c[n]];t?(0===h&&(h=Ob()),f[n]=t(d[n])):f[n]=d[n]}c=a(...f);return c=function(l){0!==h&&Pb(h);return"string"===b?l?K(A,l):"":"boolean"===b?!!l:l}(c)};
[44].forEach(a=>{gb[a]=new N(a);gb[a].stack="<generic error, no stack>"});Q=Array(4096);zb(O,"/");T("/tmp");T("/home");T("/home/web_user");(function(){T("/dev");$a(259,{read:()=>0,write:(d,e,f,h)=>h});Bb("/dev/null",259);Za(1280,bb);Za(1536,cb);Bb("/dev/tty",1280);Bb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ta(a).byteLength);return a[--b]};V("random",c);V("urandom",c);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");zb({U(){var b=fb(a,"fd",16895,73);b.N={lookup(c,d){var e=S(+d);c={parent:null,U:{pa:"fake"},N:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Sb={a:(a,b,c)=>{var d=new Ka(a);C[d.aa+16>>2]=0;C[d.aa+4>>2]=b;C[d.aa+8>>2]=c;La=a;Oa++;throw La;},d:function(a,b,c){G=c;try{var d=S(a);switch(b){case 0:var e=H();if(0>e)break;for(;P[e];)e++;return yb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=H(),d.flags|=e,0;case 12:return e=H(),sa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.X}},g:function(a,b,c){G=c;try{var d=S(a);switch(b){case 21509:return d.tty?
0:-59;case 21505:if(!d.tty)return-59;if(d.tty.V.wa){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=H();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)z[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.V.xa)for(e=H(),a=[],f=0;32>f;f++)a.push(z[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=H();return B[e>>2]=0;case 21520:return d.tty?-28:
-59;case 21531:e=H();if(!d.P.va)throw new N(59);return d.P.va(d,b,e);case 21523:if(!d.tty)return-59;d.tty.V.ya&&(f=[24,80],e=H(),sa[e>>1]=f[0],sa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof W||"ErrnoError"!==h.name)throw h;return-h.X}},h:function(a,b,c,d){G=d;try{b=b?K(A,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":S(a).path;if(0==e.length)throw new N(44);b=J(f+"/"+e)}var h=d?H():0;return U(b,
c,h).fd}catch(n){if("undefined"==typeof W||"ErrnoError"!==n.name)throw n;return-n.X}},k:()=>{za("")},o:()=>1,t:(a,b,c)=>A.copyWithin(a,b,b+c),m:()=>{Ja=!1;Hb=0},n:(a,b)=>{X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var c=setTimeout(()=>{delete X[a];Jb(()=>Rb(a,performance.now()))},b);X[a]={id:c,La:b};return 0},p:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();C[a>>2]=60*Math.max(f,e);B[b>>2]=Number(f!=e);b=h=>
{var n=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(n/60)).padStart(2,"0")}${String(n%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(L(a,A,c,17),L(b,A,d,17)):(L(a,A,d,17),L(b,A,c,17))},e:()=>Date.now(),c:()=>performance.now(),u:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
q:(a,b)=>{var c=0;Mb().forEach((d,e)=>{var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)z[e++]=d.charCodeAt(f);z[e]=0;c+=d.length+1});return 0},r:(a,b)=>{var c=Mb();C[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);C[b>>2]=d;return 0},b:a=>{ra=a;Ib(a)},f:function(a){try{var b=S(a);Db(b);return 0}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return c.X}},s:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var f,h=b=0;h<c;h++){var n=C[a>>2],t=C[a+4>>2];a+=8;var l=e,p=n,r=t,I=f,Ma=z;
if(0>r||0>I)throw new N(28);if(null===l.fd)throw new N(8);if(1===(l.flags&2097155))throw new N(8);if(16384===(l.node.mode&61440))throw new N(31);if(!l.P.read)throw new N(28);var la="undefined"!=typeof I;if(!la)I=l.position;else if(!l.seekable)throw new N(70);var ma=l.P.read(l,Ma,p,r,I);la||(l.position+=ma);var M=ma;if(0>M){var na=-1;break a}b+=M;if(M<t)break;"undefined"!=typeof f&&(f+=M)}na=b}C[d>>2]=na;return 0}catch(Na){if("undefined"==typeof W||"ErrnoError"!==Na.name)throw Na;return Na.X}},j:function(a,
b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=S(a);Eb(f,b,d);Ga=[f.position>>>0,(F=f.position,1<=+Math.abs(F)?0<F?+Math.floor(F/4294967296)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];B[e>>2]=Ga[0];B[e+4>>2]=Ga[1];f.fa&&0===b&&0===d&&(f.fa=null);return 0}catch(h){if("undefined"==typeof W||"ErrnoError"!==h.name)throw h;return h.X}},i:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var f,h=b=0;h<c;h++){var n=C[a>>2],t=C[a+4>>2];a+=8;var l=Fb(e,z,n,
t,f);if(0>l){var p=-1;break a}b+=l;if(l<t)break;"undefined"!=typeof f&&(f+=l)}p=b}C[d>>2]=p;return 0}catch(r){if("undefined"==typeof W||"ErrnoError"!==r.name)throw r;return r.X}},l:Ib},Y=function(){function a(c){Y=c.exports;pa=Y.v;ta();va.unshift(Y.w);D--;g.monitorRunDependencies?.(D);0==D&&(null!==ya&&(clearInterval(ya),ya=null),E&&(c=E,E=null,c()));return Y}var b={a:Sb};D++;g.monitorRunDependencies?.(D);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){y(`Module.instantiateWasm callback failed with error: ${c}`),
k(c)}Ba??=Aa("highs.wasm")?"highs.wasm":g.locateFile?g.locateFile("highs.wasm",v):v+"highs.wasm";Fa(b,function(c){a(c.instance)}).catch(k);return{}}(),Tb=g._Highs_create=()=>(Tb=g._Highs_create=Y.x)(),Ub=g._Highs_destroy=a=>(Ub=g._Highs_destroy=Y.y)(a),Vb=g._Highs_run=a=>(Vb=g._Highs_run=Y.z)(a);g._Highs_readModel=(a,b)=>(g._Highs_readModel=Y.A)(a,b);g._Highs_writeSolution=(a,b)=>(g._Highs_writeSolution=Y.B)(a,b);g._Highs_writeSolutionPretty=(a,b)=>(g._Highs_writeSolutionPretty=Y.C)(a,b);
g._Highs_setBoolOptionValue=(a,b,c)=>(g._Highs_setBoolOptionValue=Y.D)(a,b,c);g._Highs_setIntOptionValue=(a,b,c)=>(g._Highs_setIntOptionValue=Y.E)(a,b,c);g._Highs_setDoubleOptionValue=(a,b,c)=>(g._Highs_setDoubleOptionValue=Y.F)(a,b,c);g._Highs_setStringOptionValue=(a,b,c)=>(g._Highs_setStringOptionValue=Y.G)(a,b,c);var Wb=g._Highs_getModelStatus=a=>(Wb=g._Highs_getModelStatus=Y.H)(a);
g._Highs_call=(a,b,c,d,e,f,h,n,t,l,p,r,I,Ma,la,ma,M,na)=>(g._Highs_call=Y.I)(a,b,c,d,e,f,h,n,t,l,p,r,I,Ma,la,ma,M,na);var Rb=(a,b)=>(Rb=Y.J)(a,b),Pb=a=>(Pb=Y.K)(a),Nb=a=>(Nb=Y.L)(a),Ob=()=>(Ob=Y.M)();g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>Qb(a,b,c,f)};var Xb;E=function Yb(){Xb||Zb();Xb||(E=Yb)};
function Zb(){function a(){if(!Xb&&(Xb=!0,g.calledRun=!0,!qa)){if(!g.noFSInit&&!mb){var b,c;mb=!0;b??=g.stdin;c??=g.stdout;d??=g.stderr;b?V("stdin",b):Cb("/dev/tty","/dev/stdin");c?V("stdout",null,c):Cb("/dev/tty","/dev/stdout");d?V("stderr",null,d):Cb("/dev/tty1","/dev/stderr");U("/dev/stdin",0);U("/dev/stdout",1);U("/dev/stderr",1)}nb=!1;Ia(va);aa(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var d=g.postRun.shift();wa.unshift(d)}Ia(wa)}}
if(!(0<D)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Ia(ua);0<D||(g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Zb();g.ra=g.cwrap("Highs_readModel","number",["number","string"]);
const $b=g.cwrap("Highs_setIntOptionValue","number",["number","string","number"]),ac=g.cwrap("Highs_setDoubleOptionValue","number",["number","string","number"]),bc=g.cwrap("Highs_setStringOptionValue","number",["number","string","string"]),cc=g.cwrap("Highs_setBoolOptionValue","number",["number","string","number"]);g.sa=g.cwrap("Highs_writeSolutionPretty","number",["number","string"]);
const dc={0:"Not Set",1:"Load error",2:"Model error",3:"Presolve error",4:"Solve error",5:"Postsolve error",6:"Empty",7:"Optimal",8:"Infeasible",9:"Primal infeasible or unbounded",10:"Unbounded",11:"Bound on objective reached",12:"Target for objective reached",13:"Time limit reached",14:"Iteration limit reached",15:"Unknown"};
g.solve=function(a,b){Gb(a);const c=Tb();ec(()=>g.ra(c,"m.lp"),"read LP model (see http://web.mit.edu/lpsolve/doc/CPLEX-format.htm)");a=b||{};for(const d in a){const e=a[d];b=typeof e;let f;if("number"===b)f=fc;else if("boolean"===b)f=cc;else if("string"===b)f=bc;else throw Error(`Unsupported option value type ${e} for '${d}'`);ec(()=>f(c,d,e),`set option '${d}'`)}ec(()=>Vb(c),"solve the problem");a=dc[Wb(c,0)]||"Unknown";q.length=0;ec(()=>g.sa(c,""),"write and extract solution");Ub(c);a=gc(a);q.length=
0;ea.length=0;return a};function fc(a,b,c){let d=ac(a,b,c);-1===d&&c===(c|0)&&(d=$b(a,b,c));return d}function Z(a){return"inf"===a?1/0:"-inf"===a?-1/0:+a}const hc={Index:a=>parseInt(a),Lower:Z,Upper:Z,Primal:Z,Dual:Z};function ic(a,b){const c=b.match(/[^\s]+/g)||[],d={};for(let f=0;f<c.length;f++){if(f>=a.length)throw Error("Unable to parse solution line: "+b);var e=c[f];const h=a[f],n=hc[h];e=n?n(e):e;d[h]=e}return d}
function gc(a){if(3>q.length)throw Error("Unable to parse solution. Too few lines.");let b=jc(q[1],q[2]);a={Status:a,Columns:{},Rows:[],ObjectiveValue:NaN};for(var c=2;"Rows"!=q[c];c++){const d=ic(b,q[c]);d.Type||(d.Type="Continuous");a.Columns[d.Name]=d}b=jc(q[c+1],q[c+2]);for(c+=2;""!=q[c];c++)a.Rows.push(ic(b,q[c]));a.ObjectiveValue=Z(q[c+3].match(/Objective value: (.+)/)[1]);return a}
function jc(a,b){return[...a.matchAll(/[^\s]+/g)].filter(c=>" "!==b[c.index]||" "!==b[c.index+c[0].length-1]).map(c=>c[0])}function ec(a,b){let c;try{c=a()}catch(d){c=d}if(0!==c&&1!==c)throw Error("Unable to "+b+". HiGHS error "+c);}moduleRtn=ba;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], () => Module);
